version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: fleet_postgres
    environment:
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: fleet_pass
      POSTGRES_DB: fleet_db
    ports:
      - "5432:5432"
    volumes:
      - fleet_pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleet_user -d fleet_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fleet_pgdata: